/**
 * CENTRAL CONFIGURATION FILE
 * =========================================================================
 * Ubah semua data profil, tautan media sosial, marketplace, donasi, portofolio,
 * aplikasi premium, layanan komisi, dan playlist musik di sini dengan mudah!
 * =========================================================================
 */

export const siteConfig = {
  // --- IDENTITAS KREATOR / BRAND ---
  profile: {
    name: "Raihan Salman Alfarisy",
    brandName: "Rasfalz Studio",
    role: "Motion & Graphic Designer",
    tagline: "Creative & Energy",
    shortBio: "Aku adalah seorang Graphic Designer, Motion Designer, Video Editor, dan Content Creator yang berfokus pada pembuatan konten visual yang menarik dan berkualitas tinggi.",
    fullBio: "Selama kurang lebih 10 Tahun, aku telah mengembangkan keahlian dalam desain grafis, animasi, dan pengeditan video. Aku berkomitmen untuk memberikan hasil karya yang kreatif, inovatif, dan sesuai dengan kebutuhan klien. Dengan pengalaman yang luas dalam berbagai proyek, aku siap membantu merealisasikan visi kreatif Anda.",
    avatar: "https://files.catbox.moe/lmo2re.jpeg",
    location: "Sidoarjo, Jawa Timur, Indonesia (GMT+7)",
    status: "🟢 Close for Commissions & Collaborations",
    experienceYears: "10+",
    projectsCompleted: "450+",
    happyClients: "100+",
    rating: "4.8/5.0",
    email: "raihanalfarisy354@gmail.com",
  },

  // --- TAUTAN KONTAK UTAMA (WhatsApp & Telegram) ---
  contact: {
    whatsappNumber: "6288803293497",
    whatsappUrl: "https://wa.me/6288803293497?text=Halo%20Raihan%2C%20saya%20tertarik%20untuk%20berkolaborasi%20atau%20order%20commission.",
    telegramUsername: "alwaysraihan",
    telegramUrl: "https://t.me/alwaysraihan",
    email: "mailto:raihanalfarisy354@gmail.com",
  },

  // --- MEDIA SOSIAL & PORTOFOLIO EKSTERNAL ---
  socials: {
    instagram: {
      name: "Instagram",
      handle: "@rasfalz.std",
      url: "https://instagram.com/rasfalz.std",
      description: "Akun Pribadi, Portfolio, dan Konten Kreatif Visual.",
    },
    tiktok: {
      name: "TikTok",
      handle: "@rasfalz.std",
      url: "https://tiktok.com/@rasfalz.std",
      description: "Portofolio Motion Designer & Graphic Designer, serta konten kreatif visual pendek.",
    },
    youtube: {
      name: "YouTube",
      handle: "Raihan (Rasfalz Studio)",
      url: "https://www.youtube.com/@rasfalz-std",
      description: "Portofolio Motion Designer & Video Editor, serta konten kreatif visual panjang.",
    },
    github: {
      name: "Github",
      handle: "@farisganteng220",
      url: "https://github.com/farisganteng220",
      description: "Portofolio Basic Coding & Javascript",
    },
  },

  // --- EXTERNAL PORTFOLIO HUBS ---
  externalPortfolios: [
    {
      id: "ext-1",
      platform: "Portofolio Foriio First",
      tag: "Foriio",
      description: "Portofolio External Pertama, isinya berupa Motion Designer, Graphic Designer",
      url: "https://www.foriio.com/imnotraihan",
      icon: "Palette",
      accent: "#0052F5",
    },
    {
      id: "ext-2",
      platform: "Portofolio Foriio Second",
      tag: "Foriio",
      description: "Portofolio External Kedua, isinya berupa Motion Designer, Graphic Designer",
      url: "https://www.foriio.com/rasfalz-std",
      icon: "Layout",
      accent: "#FF9C0F",
    },
  ],

  // --- KOMUNITAS (WhatsApp & Telegram) ---
  communities: [
    {
      id: "comm-wa",
      name: "Rasfalz Studio Community",
      platform: "WhatsApp",
      badge: "Active Community",
      membersCount: "5+ Member",
      description: "Tempat sharing tips editing, preset gratis mingguan, diskusi project, dan sekedar ngobrol santai tentang dunia kreatif visual.",
      url: "https://whatsapp.com/channel/0029VamkyeL002T0wyDpA22d",
      icon: "MessageCircle",
      color: "#25D366",
      perks: [
        "Akses weekly free preset",
        "Sharing tutorial editing eksklusif",
        "Promosi Commision Editing & Jual Aplikasi Premium",
      ],
    },
    {
      id: "comm-tg",
      name: "Rasfalz Studio Channel",
      platform: "Telegram",
      badge: "Resource Hub",
      membersCount: "200+ Members",
      description: "Pusat download aset desain, sound effects (SFX), preset gratis, dan diskusi real-time.",
      url: "https://t.me/mentahanraihan3d",
      icon: "Send",
      color: "#229ED9",
      perks: [
        "Aset Preset dan Mentahan Gratis",
        "Info Buka Komisi Edit",
        "Promosi Komisi Editing & Jual Aplikasi Premium",
      ],
    },
  ],

  // --- DONASI & DUKUNGAN (Trakteer, Saweria, QRIS) ---
  donations: [
    {
      id: "don-trakteer",
      name: "Trakteer.id",
      logoText: "Traktir Boba Ice",
      tagline: "Support karya & download reward konten eksklusif",
      url: "https://trakteer.id/raihan354",
      buttonText: "Support on Trakteer",
      color: "#be1e2d",
      unit: "1 Boba Ice = Rp 3.000",
      description: "Dukungan kamu membantu saya membuat lebih banyak preset gratis, video tutorial, dan upgrade perangkat",
    },
    {
      id: "don-saweria",
      name: "Saweria.co",
      logoText: "Live Stream / Direct Tip",
      tagline: "Dukungan instan via QRIS, GoPay, OVO, Dana, ShopeePay",
      url: "https://saweria.co/raihan354",
      buttonText: "Support on Saweria",
      color: "#FA9D24",
      unit: "Min. Rp 10.000",
      description: "Kirim pesan dukungan yang akan langsung muncul di notification bar website OS ini!",
    },
    {
      id: "don-sociabuzz",
      name: "SociaBuzz",
      logoText: "Donasi dan Dukungan Kreator",
      tagline: "Dukungan instan via QRIS, GoPay, OVO, Dana, ShopeePay",
      url: "https://sociabuzz.com/imnot_r4ihan354",
      buttonText: "Support on SociaBuzz",
      color: "#2A7C13",
      unit: "Min. Rp 10.000",
      description: "Jangan Lupa Donasi dan Dukung Kami ya!",
    },
    {
      id: "don-qris",
      name: "QRIS",
      logoText: "Donasi dan Sumbangan Pakai QRIS",
      tagline: "Dukungan instan via QRIS",
      url: "https://files.catbox.moe/0wygml.jpeg",
      buttonText: "Support on QRIS",
      color: "#2196F3",
      unit: "Bebas tanpa minimum",
      description: "Jangan Lupa scan dan bayar donasi seikhlasnya",
    }
  ],

  // --- ONLINE SHOP & MARKETPLACE HUBS ---
  onlineShopPlatforms: [
    {
      id: "shop-payhip",
      name: "Payhip Digital Store",
      type: "Global Digital Assets",
      badge: "Worldwide Instant Download",
      description: "Preset Alight Motion, Capcut, Canva, After Effect, dan Blender 3D",
      rating: "No Rating Xixi",
      url: "https://payhip.com/RaihanMLTR",
      color: "#2196F3",
      icon: "Store",
      itemsCount: "1+ Products",
    },
    {
      id: "shop-shopee",
      name: "Shopee Official Merchandise",
      type: "Product Digital & Random",
      badge: "Gratis Ongkir & COD",
      description: "Aplikasi Premium, Preset Editing, Barang Elektronik, dan Mentahan",
      rating: "5.0 (5+ Sales)",
      url: "https://shopee.co.id/raihansalman354",
      color: "#EE4D2D",
      icon: "Store",
      itemsCount: "16 Items",
    },
    {
      id: "shop-sociabuzz",
      name: "SociaBuzz Digital Store",
      type: "Product Digital & Preset",
      badge: "Local Digital Assets",
      description: "Aplikasi Premium, Preset Editing, dan Mentahan",
      rating: "No Rating Hehe",
      url: "https://sociabuzz.com/imnot_r4ihan354",
      color: "#408A71",
      icon: "Store",
      itemsCount: "1+ Items",
    },
  ],

  // --- APLIKASI PREMIUM (Marketplace / App Store) ---
  premiumApps: [
    {
      id: "app-1",
      name: "Alight Motion",
      category: "Editing",
      badge: "Popular",
      badgeColor: "#408175",
      price: "Rp 6.000",
      originalPrice: "Rp 149.000",
      rating: "4.8",
      downloads: "100+",
      icon: "Video",
      thumbnail: "https://files.catbox.moe/cscuk5.png",
      description: "Akun Alight Motion Premium Private Selama 1 Tahun",
      features: [
        "Bisa Request Email Pribadi ataupun Email dari kita",
        "Tidak Ada Watermark di Video",
        "Support 5MB keatas dan membuka efek premium",
        "100% Aman tidak ada kendala",
      ],
      status: "Stok Ready",
      buyUrl: "https://wa.me/6288803293497?text=Halo%2C%20saya%20ingin%20membeli%20akun%20Alight%20Motion%20Premium%20selama%201%20Tahun.",
    },
    {
      id: "app-2",
      name: "CapCut",
      category: "Editing",
      badge: "Best",
      badgeColor: "#303841",
      price: "Rp 30.000",
      originalPrice: "Rp 145.000",
      rating: "4.9",
      downloads: "20+",
      icon: "Pipette",
      thumbnail: "https://files.catbox.moe/pej2mj.png",
      description: "Akun Capcut Premium Selama 1 Bulan",
      features: [
        "Data Akun CapCut itu dari kita",
        "Membuka Fitur Premium dari Aplikasi Capcut",
        "Tanpa Watermark di Video",
        "100% Terjamin Aman",
      ],
      status: "Stok Ready",
      buyUrl: "https://wa.me/6288803293497?text=Halo%2C%20saya%20ingin%20membeli%20akun%20CapCut%20Premium%20selama%201%20tahun.",
    },
    {
      id: "app-3",
      name: "Canva",
      category: "Editing",
      badge: "Popular",
      badgeColor: "#723EC3",
      price: "Rp 10.000",
      originalPrice: "Rp 95.000",
      rating: "4.9",
      downloads: "50+",
      icon: "Box",
      thumbnail: "https://files.catbox.moe/rlm956.png",
      description: "Akun Canva Member Selama 1 Tahun",
      features: [
        "1000+ Elemen, Font, & Template Premium",
        "Tanpa Watermark",
        "Fitur Premium Terbuka",
        "100% Terjamin Aman",
      ],
      status: "Stok Ready",
      buyUrl: "https://wa.me/6288803293497?text=Halo%2C%20saya%20ingin%20membeli%20akun%20Canva%20Member%20selama%201%20tahun.",
    },
    {
      id: "app-4",
      name: "Ibis Paint",
      category: "Editing",
      badge: "Best",
      badgeColor: "#2B2A2A",
      price: "Rp 15.000",
      originalPrice: "Rp 200.000",
      rating: "4.9",
      downloads: "50+",
      icon: "Music",
      thumbnail: "https://files.catbox.moe/act4th.png",
      description: "Akun Ibis Paint Sharing Selama 1 Tahun",
      features: [
        "Fitur Premium Terbuka",
        "Tanpa Iklan Sama Sekali",
        "Akunnya dari kita",
        "100% Terjamin Aman",
      ],
      status: "Stok Ready",
      buyUrl: "https://wa.me/6288803293497?text=Halo%2C%20saya%20ingin%20membeli%20akun%20Ibis%20Pain%20selama%201%20tahun.",
    },
  ],

  // --- COMMISSION EDITING SERVICES ---
  commissionServices: [
    {
      id: "comm-photo",
      title: "Photo Editing & Retouching",
      category: "Photography & Creative Art",
      icon: "Image",
      startingPrice: "Rp 75.000 / foto",
      turnaround: "1 - 2 Hari Kerja",
      description: "High-end skin retouching, color grading cinematic, background replacement, photomanipulation, dan branding product photos.",
      inclusions: [
        "Color grading profesional (mood custom)",
        "High-frequency skin separation retouching",
        "Pembersihan background & detail fix",
        "Output full-resolution JPEG, PNG, TIFF",
        "Revisi hingga 3 kali",
      ],
      popular: false,
    },
    {
      id: "comm-video",
      title: "Shorts / Reels / TikTok Viral Video",
      category: "Short-Form Video Editing",
      icon: "Film",
      startingPrice: "Rp 150.000 / video",
      turnaround: "1 - 3 Hari Kerja",
      description: "Editing video ritme cepat gaya Alex Hormozi/Ali Abdaal, dynamic motion subtitles, sound effect punchy, b-roll footage curated, dan visual hook.",
      inclusions: [
        "Animated karaoke-style subtitles",
        "Sound design & punchy sound effects",
        "Zoom in/out, kinetic typography, stickers",
        "Color grading & audio enhancement",
        "Rasio 9:16 siap upload Instagram/TikTok/YouTube",
      ],
      popular: true,
    },
    {
      id: "comm-graphic",
      title: "Branding & Graphic Design",
      category: "Visual Identity & Social Kit",
      icon: "PenTool",
      startingPrice: "Rp 350.000 / paket",
      turnaround: "3 - 5 Hari Kerja",
      description: "Pembuatan logo modern, visual identity guidelines, feed template social media, packaging design, dan streaming overlays.",
      inclusions: [
        "2-3 konsep desain awal",
        "File master vector (AI, EPS, SVG, PDF)",
        "Guideline warna & panduan tipografi",
        "Mockup 3D presentasi",
        "Full copyright kepemilikan",
      ],
      popular: false,
    },
    {
      id: "comm-custom",
      title: "Custom Creative Project / Full Production",
      category: "End-to-End Creative Campaign",
      icon: "Sparkles",
      startingPrice: "Custom Quote",
      turnaround: "Fleksibel Sesuai Brief",
      description: "Produksi video promosi YouTube, music video visualizer, website UI mockup prototyping, atau creative direction campaign produk.",
      inclusions: [
        "1-on-1 ideation & storyboard planning",
        "Dedicated project timeline & daily update",
        "Multi-asset delivery bundle",
        "Priority queue & unlimited adjustments",
      ],
      popular: false,
    },
  ],

  // --- PORTOFOLIO KARYA ---
  portfolioItems: [
    {
      id: "p1",
      title: "Neo-Tokyo Cyberpunk Visual Rebrand",
      category: "Branding",
      year: "2025",
      tools: ["Illustrator", "Photoshop", "Blender 3D", "Figma"],
      client: "Neon Grid Entertainment",
      image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=900&auto=format&fit=crop&q=80",
      description: "Identitas visual futuristik terinspirasi dari estetika OS retro-modern, tipografi berani, dan palet warna neon orange-biru.",
      link: "https://behance.net",
    },
    {
      id: "p2",
      title: "Pulse Tech Video Editing Campaign",
      category: "Video Editing",
      year: "2025",
      tools: ["Premiere Pro", "After Effects", "DaVinci Resolve"],
      client: "Pulse Audio Global",
      image: "https://images.unsplash.com/photo-1536240478700-b869070f9279?w=900&auto=format&fit=crop&q=80",
      description: "Seri video reel ritme cepat dengan audio sync presisi milidetik, motion tracking 3D, dan color grading dark teal-orange.",
      link: "https://youtube.com",
    },
    {
      id: "p3",
      title: "Aura Minimalist Glassmorphic UI/UX",
      category: "Digital Content",
      year: "2024",
      tools: ["Figma", "React", "CSS3", "Spline 3D"],
      client: "Aura Workspace App",
      image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=900&auto=format&fit=crop&q=80",
      description: "Desain sistem desktop & mobile OS terpadu yang memadukan ChromeOS shelf dengan launcher Android 16 Google Pixel.",
      link: "https://dribbble.com",
    },
    {
      id: "p4",
      title: "Midnight Horizon Photo Manipulation",
      category: "Photo Editing",
      year: "2024",
      tools: ["Photoshop", "Lightroom", "Midjourney"],
      client: "Personal Artwork Series",
      image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=900&auto=format&fit=crop&q=80",
      description: "Koleksi foto manipulasi lanskap metropolitan malam hari dengan pencahayaan sinematik dan tekstur atmosferik.",
      link: "https://instagram.com",
    },
    {
      id: "p5",
      title: "Kinetix Apparel Streetwear Graphics",
      category: "Graphic Design",
      year: "2024",
      tools: ["Illustrator", "CLO 3D", "Photoshop"],
      client: "Kinetix Clothing Co.",
      image: "https://images.unsplash.com/photo-1558655146-d09347e92766?w=900&auto=format&fit=crop&q=80",
      description: "Desain grafis kaos oversize dengan gaya tipografi brutalist, barcode vector, dan simbol cyberpunk.",
      link: "https://behance.net",
    },
    {
      id: "p6",
      title: "Synthwave Sound Visualizer 4K",
      category: "Other Projects",
      year: "2025",
      tools: ["After Effects", "Trapcode Form", "Cinema 4D"],
      client: "Vantara Records",
      image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=900&auto=format&fit=crop&q=80",
      description: "Visualizer audio responsif dengan frekuensi spectrum dinamis, partikel bercahaya, dan simulasi grid sintetis.",
      link: "https://youtube.com",
    },
  ],

  // --- GALLERY ITEMS ---
  galleryItems: [
    {
      id: "g1",
      title: "Cybernetic Horizon #01",
      category: "Creative Artwork",
      image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&auto=format&fit=crop&q=80",
      camera: "Blender Cycles 4.0 / Post in Photoshop",
      date: "Feb 2025",
      aspect: "landscape",
    },
    {
      id: "g2",
      title: "Neon Rain Night Photography",
      category: "Photo Collection",
      image: "https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1200&auto=format&fit=crop&q=80",
      camera: "Sony A7 IV / 35mm f/1.4 GM",
      date: "Jan 2025",
      aspect: "portrait",
    },
    {
      id: "g3",
      title: "Editing Studio Workspace Desk",
      category: "Behind The Scenes",
      image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1200&auto=format&fit=crop&q=80",
      camera: "MacBook Pro & 34\" Ultrawide Setup",
      date: "Jan 2025",
      aspect: "landscape",
    },
    {
      id: "g4",
      title: "Android 16 Glass Launcher Concept",
      category: "Project Preview",
      image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80",
      camera: "Figma Vector & CSS Prototyping",
      date: "Des 2024",
      aspect: "square",
    },
    {
      id: "g5",
      title: "Abstract Liquid Chrome & Orange",
      category: "Creative Artwork",
      image: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=1200&auto=format&fit=crop&q=80",
      camera: "Cinema 4D + Octane Render",
      date: "Nov 2024",
      aspect: "portrait",
    },
    {
      id: "g6",
      title: "Color Grading Timeline DaVinci",
      category: "Behind The Scenes",
      image: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200&auto=format&fit=crop&q=80",
      camera: "DaVinci Resolve Studio 19",
      date: "Okt 2024",
      aspect: "landscape",
    },
  ],

  // --- VISUAL IDENTITY DOCUMENTS ---
  visualIdentityDocs: [
    {
      id: "doc-1",
      name: "Vantara Master Brand Guidelines v2.5",
      type: "PDF Document",
      size: "14.8 MB",
      updated: "15 Februari 2025",
      description: "Panduan lengkap penggunaan logo, clearspace, tone of voice, filosofi brand, dan standardisasi aset digital.",
      previewImg: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=700&auto=format&fit=crop&q=80",
      downloadUrl: "#",
    },
    {
      id: "doc-2",
      name: "Logo Vector & Responsive Assets Pack",
      type: "ZIP / AI / SVG / PNG",
      size: "28.4 MB",
      updated: "10 Januari 2025",
      description: "Paket logo dalam semua format (SVG, Monochrome, Dark, Light, Favicon) lengkap dengan resolusi hingga 8K.",
      previewImg: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=700&auto=format&fit=crop&q=80",
      downloadUrl: "#",
    },
    {
      id: "doc-3",
      name: "Official Color Palette & Tokens Spec",
      type: "JSON / CSS / ASE",
      size: "2.1 MB",
      updated: "20 Februari 2025",
      description: "Spesifikasi warna Primary Orange #FF9C0F, Primary Blue #0052F5, Light Mode #F8F8FF, dan Dark Mode #040200.",
      previewImg: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=700&auto=format&fit=crop&q=80",
      downloadUrl: "#",
    },
    {
      id: "doc-4",
      name: "Typography Guidelines & Font Pairing Guide",
      type: "PDF & Spec Sheet",
      size: "8.6 MB",
      updated: "05 Februari 2025",
      description: "Aturan hierarki teks menggunakan Creato Display, Laro Soft Medium, dan font pelengkap untuk web & mobile UI.",
      previewImg: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=700&auto=format&fit=crop&q=80",
      downloadUrl: "#",
    },
  ],

  // --- VIRTUAL FILE EXPLORER (Portfolio Files) ---
  portfolioFiles: [
    {
      id: "f-1",
      name: "Neo_Tokyo_Branding_Final_8K.png",
      folder: "Branding",
      type: "PNG Image",
      size: "18.4 MB",
      modified: "24 Feb 2025",
      preview: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80",
      tags: ["Branding", "Vector", "Cyberpunk"],
    },
    {
      id: "f-2",
      name: "Pulse_Commercial_Reel_ProRes422.mov",
      folder: "Video Projects",
      type: "MOV Video",
      size: "420.5 MB",
      modified: "20 Feb 2025",
      preview: "https://images.unsplash.com/photo-1536240478700-b869070f9279?w=800&auto=format&fit=crop&q=80",
      tags: ["Video", "4K", "Premiere"],
    },
    {
      id: "f-3",
      name: "Aura_Design_System_Tokens.json",
      folder: "Graphic Design",
      type: "JSON Data",
      size: "142 KB",
      modified: "18 Feb 2025",
      preview: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
      tags: ["Design System", "Tokens", "CSS"],
    },
    {
      id: "f-4",
      name: "Midnight_Horizon_ColorGrade.cube",
      folder: "Photo Editing",
      type: "3D LUT",
      size: "1.2 MB",
      modified: "12 Feb 2025",
      preview: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
      tags: ["LUT", "Lightroom", "Color"],
    },
    {
      id: "f-5",
      name: "Vantara_Iconography_Master_Vector.svg",
      folder: "Branding",
      type: "SVG Vector",
      size: "3.4 MB",
      modified: "05 Feb 2025",
      preview: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&auto=format&fit=crop&q=80",
      tags: ["Icons", "SVG", "Vector"],
    },
    {
      id: "f-6",
      name: "Archive_2024_Client_Deliverables.zip",
      folder: "Archive",
      type: "ZIP Archive",
      size: "1.8 GB",
      modified: "31 Des 2024",
      preview: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
      tags: ["Archive", "Backup", "Zip"],
    },
  ],

  // --- PLAYLIST MUSIK BACKGROUND & MUSIC PLAYER ---
  playlist: [
    {
      id: "m1",
      title: "Kita Usahakan Rumah Itu",
      artist: "Sal Priadi",
      album: "Rasfalz Studio Picks",
      duration: "4:05",
      cover: "https://i.ytimg.com/vi/m-KsjaTEHwA/hqdefault.jpg",
      youtubeId: "m-KsjaTEHwA",
    },
    {
      id: "m2",
      title: "Secukupnya",
      artist: "Hindia",
      album: "Rasfalz Studio Picks",
      duration: "4:10",
      cover: "https://i.ytimg.com/vi/DydcU_2m6Vs/hqdefault.jpg",
      youtubeId: "DydcU_2m6Vs",
    },
    {
      id: "m3",
      title: "Ruang Sendiri",
      artist: "Tulus",
      album: "Rasfalz Studio Picks",
      duration: "4:32",
      cover: "https://i.ytimg.com/vi/eZgj6pTnNto/hqdefault.jpg",
      youtubeId: "eZgj6pTnNto",
    },
    {
      id: "m4",
      title: "To The Bone",
      artist: "Pamungkas",
      album: "Rasfalz Studio Picks",
      duration: "4:04",
      cover: "https://i.ytimg.com/vi/yPOav66A0_U/hqdefault.jpg",
      youtubeId: "yPOav66A0_U",
    },
  ],

  // --- SKILLS & TOOLS ---
  skills: [
    { name: "Premiere Pro & After Effects", level: 95, category: "Video & Motion", icon: "Film" },
    { name: "Photoshop & High-End Retouching", level: 92, category: "Graphic & Photo", icon: "Image" },
    { name: "DaVinci Resolve Color Grading", level: 88, category: "Video & Motion", icon: "Palette" },
    { name: "Figma & Design Systems", level: 90, category: "UI/UX & Product", icon: "Layout" },
    { name: "Blender 3D & Spatial Design", level: 82, category: "3D & Render", icon: "Box" },
    { name: "React, CSS3 & Creative Code", level: 85, category: "Development", icon: "Code2" },
  ],

  // --- WHAT I DO CARDS ---
  whatIDo: [
    {
      title: "Video Editing & Motion Graphics",
      description: "Membuat video pendek viral (Shorts/Reels) dan video promosi komersial dengan pacing sinematik, efek dinamis, dan sound design kelas atas.",
      icon: "Film",
      accent: "#FF9C0F",
    },
    {
      title: "High-End Photo Retouching",
      description: "Manipulasi foto artistik, color grading sinematik, dan retouching kecantikan beresolusi tinggi untuk brand dan kreator.",
      icon: "Image",
      accent: "#0052F5",
    },
    {
      title: "UI/UX & Digital OS Design",
      description: "Merancang antarmuka sistem operasi, dashboard web modern berkonsep glassmorphic, dan prototipe aplikasi mobile responsif.",
      icon: "Layout",
      accent: "#FF9C0F",
    },
    {
      title: "Creative Tools & Asset Creation",
      description: "Mengembangkan plugin pengeditan, preset LUTs warna, sound pack eksklusif, dan toolkit produktivitas untuk komunitas kreatif.",
      icon: "Sparkles",
      accent: "#0052F5",
    },
  ],
};
