/**
 * CENTRAL CONFIGURATION FILE
 * =========================================================================
 * Ubah semua data profil, tautan media sosial, marketplace, donasi, portofolio,
 * aplikasi premium, layanan komisi, dan playlist musik di sini dengan mudah!
 * =========================================================================
 */

export const siteConfig = {
  // --- IDENTITAS KREATOR / BRAND ---
  profile: {
    name: "Alex Vantara",
    brandName: "Vantara Studio OS",
    role: "Visual Creator & Creative Technologist",
    tagline: "Crafting High-Impact Visuals, Digital Tools & Cyberpunk Experiences",
    shortBio: "Multidisciplinary Visual Designer, Video Editor, and Creative Developer specializing in aesthetic OS design, visual identities, and interactive digital products.",
    fullBio: "Over the past 6+ years, I have worked with global brands, digital creators, and innovative agencies to build captivating visual identities, high-converting video edits, and custom digital software tools. My philosophy bridges modern OS interfaces with high-end digital aesthetics.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80",
    location: "Jakarta, Indonesia (GMT+7)",
    status: "🟢 Open for Commissions & Collaborations",
    experienceYears: "6+",
    projectsCompleted: "350+",
    happyClients: "180+",
    rating: "4.9/5.0",
    email: "contact@alexvantara.design",
  },

  // --- TAUTAN KONTAK UTAMA (WhatsApp & Telegram) ---
  contact: {
    whatsappNumber: "6281234567890",
    whatsappUrl: "https://wa.me/6281234567890?text=Halo%20Alex%2C%20saya%20tertarik%20untuk%20berkolaborasi%20atau%20order%20commission.",
    telegramUsername: "alexvantara",
    telegramUrl: "https://t.me/alexvantara",
    email: "mailto:contact@alexvantara.design",
  },

  // --- MEDIA SOSIAL & PORTOFOLIO EKSTERNAL ---
  socials: {
    instagram: {
      name: "Instagram",
      handle: "@alexvantara.id",
      url: "https://instagram.com/alexvantara.id",
      description: "Daily visual explorations, reels & behind-the-scenes.",
    },
    tiktok: {
      name: "TikTok",
      handle: "@vantara.creative",
      url: "https://tiktok.com/@vantara.creative",
      description: "Quick editing tutorials, workflow tips & viral edits.",
    },
    youtube: {
      name: "YouTube",
      handle: "Vantara Creative Hub",
      url: "https://youtube.com/@vantara_creative",
      description: "In-depth editing breakdowns, software masterclasses & sound design.",
    },
    behance: {
      name: "Behance",
      handle: "alexvantara",
      url: "https://behance.net/alexvantara",
      description: "Curated case studies & high-resolution project showcases.",
    },
    dribbble: {
      name: "Dribbble",
      handle: "alexvantara",
      url: "https://dribbble.com/alexvantara",
      description: "UI/UX shots, app concepts & micro-interactions.",
    },
  },

  // --- EXTERNAL PORTFOLIO HUBS ---
  externalPortfolios: [
    {
      id: "ext-1",
      platform: "Behance Master Collection",
      tag: "Case Studies",
      description: "Comprehensive case studies with complete creative workflows, typography & layouts.",
      url: "https://behance.net/alexvantara",
      icon: "Palette",
      accent: "#0052F5",
    },
    {
      id: "ext-2",
      platform: "Dribbble UI Design Space",
      tag: "UI/UX & OS",
      description: "Interactive prototypes, mobile launchers, and glassmorphic dashboards.",
      url: "https://dribbble.com/alexvantara",
      icon: "Layout",
      accent: "#FF9C0F",
    },
    {
      id: "ext-3",
      platform: "Vimeo Showreel 4K",
      tag: "Video Editing",
      description: "High bitrate 4K commercial edits, color grading reels, and sound design breakdowns.",
      url: "https://vimeo.com",
      icon: "Film",
      accent: "#0052F5",
    },
    {
      id: "ext-4",
      platform: "ArtStation Concept Art",
      tag: "3D & Matte Painting",
      description: "Futuristic concept arts, 3D blender sceneries, and cinematic matte paintings.",
      url: "https://artstation.com",
      icon: "Sparkles",
      accent: "#FF9C0F",
    },
  ],

  // --- KOMUNITAS (WhatsApp & Telegram) ---
  communities: [
    {
      id: "comm-wa",
      name: "Vantara Creator VIP Community",
      platform: "WhatsApp",
      badge: "Active Community",
      membersCount: "2,400+ Creators",
      description: "Tempat sharing tips editing, preset gratis mingguan, diskusi project, dan info lowongan freelance kreatif.",
      url: "https://chat.whatsapp.com/sampleInviteLink123",
      icon: "MessageCircle",
      color: "#25D366",
      perks: [
        "Akses weekly free preset & LUTs",
        "Feedback & review karya kamu langsung",
        "Info job & kolaborasi freelance",
        "Sharing tutorial editing eksklusif",
      ],
    },
    {
      id: "comm-tg",
      name: "Vantara Digital OS Channel & Lounge",
      platform: "Telegram",
      badge: "Resource Hub",
      membersCount: "5,800+ Members",
      description: "Pusat download aset desain, sound effects (SFX), plugin gratis, template Premiere & After Effects, dan diskusi real-time.",
      url: "https://t.me/vantara_creatives",
      icon: "Send",
      color: "#229ED9",
      perks: [
        "Cloud storage resource download cepat",
        "Diskon khusus produk digital & apps",
        "Live Q&A setiap akhir pekan",
        "Bot notifikasi update preset baru",
      ],
    },
  ],

  // --- DONASI & DUKUNGAN (Trakteer, Saweria, QRIS) ---
  donations: [
    {
      id: "don-trakteer",
      name: "Trakteer.id",
      logoText: "Traktir Kopi / Cendol",
      tagline: "Support karya & download reward konten eksklusif",
      url: "https://trakteer.id/alexvantara",
      buttonText: "Support on Trakteer",
      color: "#be1e2d",
      unit: "1 Cendol = Rp 5.000",
      description: "Dukungan kamu membantu saya membuat lebih banyak preset gratis, video tutorial, dan open-source tools!",
    },
    {
      id: "don-saweria",
      name: "Saweria.co",
      logoText: "Live Stream / Direct Tip",
      tagline: "Dukungan instan via QRIS, GoPay, OVO, Dana, ShopeePay",
      url: "https://saweria.co/alexvantara",
      buttonText: "Support on Saweria",
      color: "#FA9D24",
      unit: "Min. Rp 10.000",
      description: "Kirim pesan dukungan yang akan langsung muncul di notification bar website OS ini!",
    },
  ],

  // --- ONLINE SHOP & MARKETPLACE HUBS ---
  onlineShopPlatforms: [
    {
      id: "shop-gumroad",
      name: "Gumroad Digital Store",
      type: "Global Digital Assets",
      badge: "Worldwide Instant Download",
      description: "Preset Lightroom, After Effects Templates, 3D Assets, dan Sound Design Packs berkualitas tinggi.",
      rating: "5.0 (420+ Reviews)",
      url: "https://gumroad.com",
      color: "#FF90E8",
      icon: "ShoppingBag",
      itemsCount: "24 Products",
    },
    {
      id: "shop-shopee",
      name: "Shopee Official Merchandise",
      type: "Physical & Digital Merchandise",
      badge: "Gratis Ongkir & COD",
      description: "Kaos apparel streetwear desain futuristik, sticker pack OS edition, mousepad XL, dan flashdisk resource kit.",
      rating: "4.9 (850+ Sales)",
      url: "https://shopee.co.id",
      color: "#EE4D2D",
      icon: "Store",
      itemsCount: "16 Items",
    },
    {
      id: "shop-tokopedia",
      name: "Tokopedia Official Store",
      type: "Tech & Creative Gear",
      badge: "Power Merchant Pro",
      description: "Custom macro keypad untuk editing, deskmat aesthetic, dan bundle flashdrive video editing assets.",
      rating: "4.9 (530+ Reviews)",
      url: "https://tokopedia.com",
      color: "#03AC0E",
      icon: "PackageCheck",
      itemsCount: "12 Items",
    },
    {
      id: "shop-lemon",
      name: "Lemon Squeezy Store",
      type: "Software License & Add-ons",
      badge: "Instant License Keys",
      description: "Beli lisensi premium apps, AI video workflow scripts, dan automated premiere panel extensions.",
      rating: "4.98 (310+ Customers)",
      url: "https://lemonsqueezy.com",
      color: "#7047EB",
      icon: "Zap",
      itemsCount: "8 Software Tools",
    },
  ],

  // --- APLIKASI PREMIUM (Marketplace / App Store) ---
  premiumApps: [
    {
      id: "app-1",
      name: "Chronos Edit Pro",
      category: "Editing",
      badge: "Popular",
      badgeColor: "#FF9C0F",
      price: "Rp 149.000",
      originalPrice: "Rp 299.000",
      rating: "4.9",
      downloads: "1.8k+",
      icon: "Video",
      thumbnail: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=700&auto=format&fit=crop&q=80",
      description: "Extension panel canggih untuk Premiere Pro & After Effects dengan 500+ transisi halus, auto-subtitles AI generator, dan smart sound syncer.",
      features: [
        "1-Click Smart Transition Builder",
        "Auto Audio Ducking & SFX Matcher",
        "500+ Presets Color Grading Cinematic (LUTs)",
        "Lifetime Updates & Dedicated Discord Support",
      ],
      status: "Available v2.4",
      buyUrl: "https://wa.me/6281234567890?text=Halo%2C%20saya%20ingin%20membeli%20aplikasi%20Chronos%20Edit%20Pro.",
    },
    {
      id: "app-2",
      name: "Vantara Palette OS",
      category: "Productivity",
      badge: "Recommended",
      badgeColor: "#0052F5",
      price: "Rp 99.000",
      originalPrice: "Rp 189.000",
      rating: "5.0",
      downloads: "940+",
      icon: "Pipette",
      thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=700&auto=format&fit=crop&q=80",
      description: "Color harmony generator & WCAG contrast audit tool untuk UI/UX Designer. Export langsung ke CSS variable, Tailwind config, atau Figma token.",
      features: [
        "AI Harmonizer dengan 10+ Color Theory Engines",
        "Instant Export ke Tailwind, CSS Vars, Figma",
        "Realtime Glassmorphism Simulator",
        "Accessibility Contrast Auto-Fixer",
      ],
      status: "Available v3.1",
      buyUrl: "https://wa.me/6281234567890?text=Halo%2C%20saya%20ingin%20membeli%20aplikasi%20Vantara%20Palette%20OS.",
    },
    {
      id: "app-3",
      name: "Lumina Frame 3D",
      category: "Premium Tools",
      badge: "New",
      badgeColor: "#10B981",
      price: "Rp 189.000",
      originalPrice: "Rp 350.000",
      rating: "4.8",
      downloads: "480+",
      icon: "Box",
      thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=700&auto=format&fit=crop&q=80",
      description: "Mockup generator 3D interaktif untuk device Android 16 Pixel, iPhone, dan ChromeOS display. Render video 60fps dengan animasi mulus.",
      features: [
        "100+ Model Mockup 3D Photorealistic",
        "Custom Lighting & Dynamic Reflections",
        "Export Video MP4, GIF, dan High-res PNG",
        "Support Import Video Screen Recording",
      ],
      status: "Available v1.0",
      buyUrl: "https://wa.me/6281234567890?text=Halo%2C%20saya%20ingin%20membeli%20aplikasi%20Lumina%20Frame%203D.",
    },
    {
      id: "app-4",
      name: "SoundWave CyberFX",
      category: "Utility",
      badge: "Premium",
      badgeColor: "#8B5CF6",
      price: "Rp 129.000",
      originalPrice: "Rp 249.000",
      rating: "4.9",
      downloads: "1.2k+",
      icon: "Music",
      thumbnail: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=700&auto=format&fit=crop&q=80",
      description: "Pustaka 1.500+ sound effects futuristik, UI clicks, whooshes, cinematic risers, dan ambient droning lo-fi bebas royalti selamanya.",
      features: [
        "1,500+ High Definition WAV / 24-bit 96kHz Files",
        "Meta-tagged & Searchable di Premiere / DaVinci",
        "100% Bebas Royalti untuk YouTube & Komersial",
        "Modular Synth Sound Constructor",
      ],
      status: "Available v4.0",
      buyUrl: "https://wa.me/6281234567890?text=Halo%2C%20saya%20ingin%20membeli%20SoundWave%20CyberFX.",
    },
  ],

  // --- COMMISSION EDITING SERVICES ---
  commissionServices: [
    {
      id: "comm-photo",
      title: "Photo Editing & Retouching",
      category: "Photography & Creative Art",
      icon: "Image",
      startingPrice: "Rp 75.000 / foto",
      turnaround: "1 - 2 Hari Kerja",
      description: "High-end skin retouching, color grading cinematic, background replacement, photomanipulation, dan branding product photos.",
      inclusions: [
        "Color grading profesional (mood custom)",
        "High-frequency skin separation retouching",
        "Pembersihan background & detail fix",
        "Output full-resolution JPEG, PNG, TIFF",
        "Revisi hingga 3 kali",
      ],
      popular: false,
    },
    {
      id: "comm-video",
      title: "Shorts / Reels / TikTok Viral Video",
      category: "Short-Form Video Editing",
      icon: "Film",
      startingPrice: "Rp 150.000 / video",
      turnaround: "1 - 3 Hari Kerja",
      description: "Editing video ritme cepat gaya Alex Hormozi/Ali Abdaal, dynamic motion subtitles, sound effect punchy, b-roll footage curated, dan visual hook.",
      inclusions: [
        "Animated karaoke-style subtitles",
        "Sound design & punchy sound effects",
        "Zoom in/out, kinetic typography, stickers",
        "Color grading & audio enhancement",
        "Rasio 9:16 siap upload Instagram/TikTok/YouTube",
      ],
      popular: true,
    },
    {
      id: "comm-graphic",
      title: "Branding & Graphic Design",
      category: "Visual Identity & Social Kit",
      icon: "PenTool",
      startingPrice: "Rp 350.000 / paket",
      turnaround: "3 - 5 Hari Kerja",
      description: "Pembuatan logo modern, visual identity guidelines, feed template social media, packaging design, dan streaming overlays.",
      inclusions: [
        "2-3 konsep desain awal",
        "File master vector (AI, EPS, SVG, PDF)",
        "Guideline warna & panduan tipografi",
        "Mockup 3D presentasi",
        "Full copyright kepemilikan",
      ],
      popular: false,
    },
    {
      id: "comm-custom",
      title: "Custom Creative Project / Full Production",
      category: "End-to-End Creative Campaign",
      icon: "Sparkles",
      startingPrice: "Custom Quote",
      turnaround: "Fleksibel Sesuai Brief",
      description: "Produksi video promosi YouTube, music video visualizer, website UI mockup prototyping, atau creative direction campaign produk.",
      inclusions: [
        "1-on-1 ideation & storyboard planning",
        "Dedicated project timeline & daily update",
        "Multi-asset delivery bundle",
        "Priority queue & unlimited adjustments",
      ],
      popular: false,
    },
  ],

  // --- PORTOFOLIO KARYA ---
  portfolioItems: [
    {
      id: "p1",
      title: "Neo-Tokyo Cyberpunk Visual Rebrand",
      category: "Branding",
      year: "2025",
      tools: ["Illustrator", "Photoshop", "Blender 3D", "Figma"],
      client: "Neon Grid Entertainment",
      image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=900&auto=format&fit=crop&q=80",
      description: "Identitas visual futuristik terinspirasi dari estetika OS retro-modern, tipografi berani, dan palet warna neon orange-biru.",
      link: "https://behance.net",
    },
    {
      id: "p2",
      title: "Pulse Tech Video Editing Campaign",
      category: "Video Editing",
      year: "2025",
      tools: ["Premiere Pro", "After Effects", "DaVinci Resolve"],
      client: "Pulse Audio Global",
      image: "https://images.unsplash.com/photo-1536240478700-b869070f9279?w=900&auto=format&fit=crop&q=80",
      description: "Seri video reel ritme cepat dengan audio sync presisi milidetik, motion tracking 3D, dan color grading dark teal-orange.",
      link: "https://youtube.com",
    },
    {
      id: "p3",
      title: "Aura Minimalist Glassmorphic UI/UX",
      category: "Digital Content",
      year: "2024",
      tools: ["Figma", "React", "CSS3", "Spline 3D"],
      client: "Aura Workspace App",
      image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=900&auto=format&fit=crop&q=80",
      description: "Desain sistem desktop & mobile OS terpadu yang memadukan ChromeOS shelf dengan launcher Android 16 Google Pixel.",
      link: "https://dribbble.com",
    },
    {
      id: "p4",
      title: "Midnight Horizon Photo Manipulation",
      category: "Photo Editing",
      year: "2024",
      tools: ["Photoshop", "Lightroom", "Midjourney"],
      client: "Personal Artwork Series",
      image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=900&auto=format&fit=crop&q=80",
      description: "Koleksi foto manipulasi lanskap metropolitan malam hari dengan pencahayaan sinematik dan tekstur atmosferik.",
      link: "https://instagram.com",
    },
    {
      id: "p5",
      title: "Kinetix Apparel Streetwear Graphics",
      category: "Graphic Design",
      year: "2024",
      tools: ["Illustrator", "CLO 3D", "Photoshop"],
      client: "Kinetix Clothing Co.",
      image: "https://images.unsplash.com/photo-1558655146-d09347e92766?w=900&auto=format&fit=crop&q=80",
      description: "Desain grafis kaos oversize dengan gaya tipografi brutalist, barcode vector, dan simbol cyberpunk.",
      link: "https://behance.net",
    },
    {
      id: "p6",
      title: "Synthwave Sound Visualizer 4K",
      category: "Other Projects",
      year: "2025",
      tools: ["After Effects", "Trapcode Form", "Cinema 4D"],
      client: "Vantara Records",
      image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=900&auto=format&fit=crop&q=80",
      description: "Visualizer audio responsif dengan frekuensi spectrum dinamis, partikel bercahaya, dan simulasi grid sintetis.",
      link: "https://youtube.com",
    },
  ],

  // --- GALLERY ITEMS ---
  galleryItems: [
    {
      id: "g1",
      title: "Cybernetic Horizon #01",
      category: "Creative Artwork",
      image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&auto=format&fit=crop&q=80",
      camera: "Blender Cycles 4.0 / Post in Photoshop",
      date: "Feb 2025",
      aspect: "landscape",
    },
    {
      id: "g2",
      title: "Neon Rain Night Photography",
      category: "Photo Collection",
      image: "https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1200&auto=format&fit=crop&q=80",
      camera: "Sony A7 IV / 35mm f/1.4 GM",
      date: "Jan 2025",
      aspect: "portrait",
    },
    {
      id: "g3",
      title: "Editing Studio Workspace Desk",
      category: "Behind The Scenes",
      image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1200&auto=format&fit=crop&q=80",
      camera: "MacBook Pro & 34\" Ultrawide Setup",
      date: "Jan 2025",
      aspect: "landscape",
    },
    {
      id: "g4",
      title: "Android 16 Glass Launcher Concept",
      category: "Project Preview",
      image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80",
      camera: "Figma Vector & CSS Prototyping",
      date: "Des 2024",
      aspect: "square",
    },
    {
      id: "g5",
      title: "Abstract Liquid Chrome & Orange",
      category: "Creative Artwork",
      image: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=1200&auto=format&fit=crop&q=80",
      camera: "Cinema 4D + Octane Render",
      date: "Nov 2024",
      aspect: "portrait",
    },
    {
      id: "g6",
      title: "Color Grading Timeline DaVinci",
      category: "Behind The Scenes",
      image: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200&auto=format&fit=crop&q=80",
      camera: "DaVinci Resolve Studio 19",
      date: "Okt 2024",
      aspect: "landscape",
    },
  ],

  // --- VISUAL IDENTITY DOCUMENTS ---
  visualIdentityDocs: [
    {
      id: "doc-1",
      name: "Vantara Master Brand Guidelines v2.5",
      type: "PDF Document",
      size: "14.8 MB",
      updated: "15 Februari 2025",
      description: "Panduan lengkap penggunaan logo, clearspace, tone of voice, filosofi brand, dan standardisasi aset digital.",
      previewImg: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=700&auto=format&fit=crop&q=80",
      downloadUrl: "#",
    },
    {
      id: "doc-2",
      name: "Logo Vector & Responsive Assets Pack",
      type: "ZIP / AI / SVG / PNG",
      size: "28.4 MB",
      updated: "10 Januari 2025",
      description: "Paket logo dalam semua format (SVG, Monochrome, Dark, Light, Favicon) lengkap dengan resolusi hingga 8K.",
      previewImg: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=700&auto=format&fit=crop&q=80",
      downloadUrl: "#",
    },
    {
      id: "doc-3",
      name: "Official Color Palette & Tokens Spec",
      type: "JSON / CSS / ASE",
      size: "2.1 MB",
      updated: "20 Februari 2025",
      description: "Spesifikasi warna Primary Orange #FF9C0F, Primary Blue #0052F5, Light Mode #F8F8FF, dan Dark Mode #040200.",
      previewImg: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=700&auto=format&fit=crop&q=80",
      downloadUrl: "#",
    },
    {
      id: "doc-4",
      name: "Typography Guidelines & Font Pairing Guide",
      type: "PDF & Spec Sheet",
      size: "8.6 MB",
      updated: "05 Februari 2025",
      description: "Aturan hierarki teks menggunakan Creato Display, Laro Soft Medium, dan font pelengkap untuk web & mobile UI.",
      previewImg: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=700&auto=format&fit=crop&q=80",
      downloadUrl: "#",
    },
  ],

  // --- VIRTUAL FILE EXPLORER (Portfolio Files) ---
  portfolioFiles: [
    {
      id: "f-1",
      name: "Neo_Tokyo_Branding_Final_8K.png",
      folder: "Branding",
      type: "PNG Image",
      size: "18.4 MB",
      modified: "24 Feb 2025",
      preview: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80",
      tags: ["Branding", "Vector", "Cyberpunk"],
    },
    {
      id: "f-2",
      name: "Pulse_Commercial_Reel_ProRes422.mov",
      folder: "Video Projects",
      type: "MOV Video",
      size: "420.5 MB",
      modified: "20 Feb 2025",
      preview: "https://images.unsplash.com/photo-1536240478700-b869070f9279?w=800&auto=format&fit=crop&q=80",
      tags: ["Video", "4K", "Premiere"],
    },
    {
      id: "f-3",
      name: "Aura_Design_System_Tokens.json",
      folder: "Graphic Design",
      type: "JSON Data",
      size: "142 KB",
      modified: "18 Feb 2025",
      preview: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
      tags: ["Design System", "Tokens", "CSS"],
    },
    {
      id: "f-4",
      name: "Midnight_Horizon_ColorGrade.cube",
      folder: "Photo Editing",
      type: "3D LUT",
      size: "1.2 MB",
      modified: "12 Feb 2025",
      preview: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
      tags: ["LUT", "Lightroom", "Color"],
    },
    {
      id: "f-5",
      name: "Vantara_Iconography_Master_Vector.svg",
      folder: "Branding",
      type: "SVG Vector",
      size: "3.4 MB",
      modified: "05 Feb 2025",
      preview: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&auto=format&fit=crop&q=80",
      tags: ["Icons", "SVG", "Vector"],
    },
    {
      id: "f-6",
      name: "Archive_2024_Client_Deliverables.zip",
      folder: "Archive",
      type: "ZIP Archive",
      size: "1.8 GB",
      modified: "31 Des 2024",
      preview: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
      tags: ["Archive", "Backup", "Zip"],
    },
  ],

  // --- PLAYLIST MUSIK BACKGROUND & MUSIC PLAYER ---
  playlist: [
    {
      id: "m1",
      title: "Midnight Cyber Skyline",
      artist: "Vantara Synthetics",
      album: "Digital OS Experience",
      duration: "3:42",
      cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&auto=format&fit=crop&q=80",
      audioFrequency: [45, 60, 80, 110, 95, 70, 85, 120, 130, 90, 65, 45],
      synthNote: 220,
    },
    {
      id: "m2",
      title: "Tokyo Neon Drift Lo-Fi",
      artist: "Kitsune Beats",
      album: "Chillwave Horizons",
      duration: "2:58",
      cover: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&auto=format&fit=crop&q=80",
      audioFrequency: [30, 50, 75, 90, 85, 65, 70, 95, 80, 60, 40, 30],
      synthNote: 261.63,
    },
    {
      id: "m3",
      title: "Glassmorphic Dreams",
      artist: "Aura Ambience",
      album: "FydeOS Soundscapes",
      duration: "4:15",
      cover: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80",
      audioFrequency: [55, 70, 95, 130, 110, 85, 100, 140, 150, 115, 75, 50],
      synthNote: 329.63,
    },
    {
      id: "m4",
      title: "Pixel Pulse 128BPM",
      artist: "Android Quantum",
      album: "QPR2 Frequency",
      duration: "3:10",
      cover: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&auto=format&fit=crop&q=80",
      audioFrequency: [70, 90, 120, 160, 140, 110, 130, 180, 190, 140, 90, 60],
      synthNote: 392.00,
    },
  ],

  // --- SKILLS & TOOLS ---
  skills: [
    { name: "Premiere Pro & After Effects", level: 95, category: "Video & Motion", icon: "Film" },
    { name: "Photoshop & High-End Retouching", level: 92, category: "Graphic & Photo", icon: "Image" },
    { name: "DaVinci Resolve Color Grading", level: 88, category: "Video & Motion", icon: "Palette" },
    { name: "Figma & Design Systems", level: 90, category: "UI/UX & Product", icon: "Layout" },
    { name: "Blender 3D & Spatial Design", level: 82, category: "3D & Render", icon: "Box" },
    { name: "React, CSS3 & Creative Code", level: 85, category: "Development", icon: "Code2" },
  ],

  // --- WHAT I DO CARDS ---
  whatIDo: [
    {
      title: "Video Editing & Motion Graphics",
      description: "Membuat video pendek viral (Shorts/Reels) dan video promosi komersial dengan pacing sinematik, efek dinamis, dan sound design kelas atas.",
      icon: "Film",
      accent: "#FF9C0F",
    },
    {
      title: "High-End Photo Retouching",
      description: "Manipulasi foto artistik, color grading sinematik, dan retouching kecantikan beresolusi tinggi untuk brand dan kreator.",
      icon: "Image",
      accent: "#0052F5",
    },
    {
      title: "UI/UX & Digital OS Design",
      description: "Merancang antarmuka sistem operasi, dashboard web modern berkonsep glassmorphic, dan prototipe aplikasi mobile responsif.",
      icon: "Layout",
      accent: "#FF9C0F",
    },
    {
      title: "Creative Tools & Asset Creation",
      description: "Mengembangkan plugin pengeditan, preset LUTs warna, sound pack eksklusif, dan toolkit produktivitas untuk komunitas kreatif.",
      icon: "Sparkles",
      accent: "#0052F5",
    },
  ],
};
